# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ulp/ulp.bd
# Block Designs: The module: 'ulp' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ulp/ip/ulp_ii_level0_wire_0/ulp_ii_level0_wire_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_0 || ORIG_REF_NAME==ulp_ii_level0_wire_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_bram_ctrl_0_0/ulp_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ulp_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_bram_ctrl_0_bram_0/ulp_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==ulp_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_0_0/ulp_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_0_0 || ORIG_REF_NAME==ulp_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_0_p_0/ulp_axi_interconnect_0_p_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_0_p_0 || ORIG_REF_NAME==ulp_axi_interconnect_0_p_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_1_0/ulp_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_1_0 || ORIG_REF_NAME==ulp_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_0_0/ulp_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_0_0 || ORIG_REF_NAME==ulp_axi_vip_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_0_p_0/ulp_axi_vip_0_p_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_0_p_0 || ORIG_REF_NAME==ulp_axi_vip_0_p_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ddr1_clk_bufg_0/ulp_ddr1_clk_bufg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ddr1_clk_bufg_0 || ORIG_REF_NAME==ulp_ddr1_clk_bufg_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ddr1_clk_ibufds_0/ulp_ddr1_clk_ibufds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ddr1_clk_ibufds_0 || ORIG_REF_NAME==ulp_ddr1_clk_ibufds_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ddrmem_1_0/ulp_ddrmem_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ddrmem_1_0 || ORIG_REF_NAME==ulp_ddrmem_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_0_0/ulp_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_0_0 || ORIG_REF_NAME==ulp_xlslice_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_1_0/ulp_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_1_0 || ORIG_REF_NAME==ulp_xlslice_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_2_0/ulp_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_2_0 || ORIG_REF_NAME==ulp_xlslice_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_3_0/ulp_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_3_0 || ORIG_REF_NAME==ulp_xlslice_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_4_0/ulp_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_4_0 || ORIG_REF_NAME==ulp_xlslice_4_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_0/ulp_xlconcat_interrupt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_0_0/ulp_xlconcat_interrupt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_0_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_1_0/ulp_xlconcat_interrupt_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_1_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_2_0/ulp_xlconcat_interrupt_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_2_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_3_0/ulp_xlconcat_interrupt_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_3_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconstant_gnd_0/ulp_xlconstant_gnd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconstant_gnd_0 || ORIG_REF_NAME==ulp_xlconstant_gnd_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_ddrmem_n_1_0/ulp_psreset_ddrmem_n_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_ddrmem_n_1_0 || ORIG_REF_NAME==ulp_psreset_ddrmem_n_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_periph_null_0/ulp_regslice_periph_null_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_periph_null_0 || ORIG_REF_NAME==ulp_regslice_periph_null_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_user_debug_bridge_0/ulp_user_debug_bridge_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_user_debug_bridge_0 || ORIG_REF_NAME==ulp_user_debug_bridge_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_debug_bridge_xsdbm_0/ulp_debug_bridge_xsdbm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_debug_bridge_xsdbm_0 || ORIG_REF_NAME==ulp_debug_bridge_xsdbm_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_fpga_dna_module_0_0/ulp_fpga_dna_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_fpga_dna_module_0_0 || ORIG_REF_NAME==ulp_fpga_dna_module_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_protocol_convert_0_0/ulp_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_protocol_convert_0_0 || ORIG_REF_NAME==ulp_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_cdc_data_static_0/ulp_axi_cdc_data_static_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_cdc_data_static_0 || ORIG_REF_NAME==ulp_axi_cdc_data_static_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_cdc_data_static1_0/ulp_axi_cdc_data_static1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_cdc_data_static1_0 || ORIG_REF_NAME==ulp_axi_cdc_data_static1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_gpio_null_0/ulp_axi_gpio_null_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_gpio_null_0 || ORIG_REF_NAME==ulp_axi_gpio_null_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_0_1/ulp_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_0_1 || ORIG_REF_NAME==ulp_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_ctrl_mgntpf_0/ulp_axi_vip_ctrl_mgntpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_ctrl_mgntpf_0 || ORIG_REF_NAME==ulp_axi_vip_ctrl_mgntpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_ctrl_userpf_0/ulp_axi_vip_ctrl_userpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_ctrl_userpf_0 || ORIG_REF_NAME==ulp_axi_vip_ctrl_userpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_data_static_0/ulp_axi_vip_data_static_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_data_static_0 || ORIG_REF_NAME==ulp_axi_vip_data_static_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_data_static1_0/ulp_axi_vip_data_static1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_data_static1_0 || ORIG_REF_NAME==ulp_axi_vip_data_static1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_freq_counter_0_0/ulp_freq_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_freq_counter_0_0 || ORIG_REF_NAME==ulp_freq_counter_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_interconnect_axilite_user_0/ulp_interconnect_axilite_user_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_interconnect_axilite_user_0 || ORIG_REF_NAME==ulp_interconnect_axilite_user_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_control_mgntpf_0/ulp_regslice_control_mgntpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_control_mgntpf_0 || ORIG_REF_NAME==ulp_regslice_control_mgntpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_control_userpf_0/ulp_regslice_control_userpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_control_userpf_0 || ORIG_REF_NAME==ulp_regslice_control_userpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_data_static_0/ulp_regslice_data_static_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_data_static_0 || ORIG_REF_NAME==ulp_regslice_data_static_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_data_static1_0/ulp_regslice_data_static1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_data_static1_0 || ORIG_REF_NAME==ulp_regslice_data_static1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_logic_reset_op_0/ulp_logic_reset_op_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_logic_reset_op_0 || ORIG_REF_NAME==ulp_logic_reset_op_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_control_0/ulp_psreset_gate_pr_control_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_control_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_control_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_data_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_data_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_ddrmem_1_0/ulp_psreset_gate_pr_ddrmem_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_ddrmem_1_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_ddrmem_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_kernel_0/ulp_psreset_gate_pr_kernel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_kernel_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_kernel_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_kernel2_0/ulp_psreset_gate_pr_kernel2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_kernel2_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_kernel2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_3/ulp_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_3 || ORIG_REF_NAME==ulp_xbar_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_2/ulp_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_2 || ORIG_REF_NAME==ulp_xbar_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_5/ulp_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_5 || ORIG_REF_NAME==ulp_xbar_5} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_4/ulp_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_4 || ORIG_REF_NAME==ulp_xbar_4} -quiet] -quiet

# IP: bd/ulp/ip/ulp_krnl_ro_rtl_1_0/ulp_krnl_ro_rtl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_krnl_ro_rtl_1_0 || ORIG_REF_NAME==ulp_krnl_ro_rtl_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_irq_const_tieoff_0/ulp_irq_const_tieoff_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_irq_const_tieoff_0 || ORIG_REF_NAME==ulp_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_0 || ORIG_REF_NAME==ulp_auto_cc_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_22/ulp_s00_regslice_22.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_22 || ORIG_REF_NAME==ulp_s00_regslice_22} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m00_regslice_0/ulp_m00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m00_regslice_0 || ORIG_REF_NAME==ulp_m00_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m01_regslice_0/ulp_m01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m01_regslice_0 || ORIG_REF_NAME==ulp_m01_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_1/ulp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_1 || ORIG_REF_NAME==ulp_auto_cc_1} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_19/ulp_s00_regslice_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_19 || ORIG_REF_NAME==ulp_s00_regslice_19} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s01_regslice_1/ulp_s01_regslice_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s01_regslice_1 || ORIG_REF_NAME==ulp_s01_regslice_1} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_us_cc_df_0/ulp_auto_us_cc_df_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_us_cc_df_0 || ORIG_REF_NAME==ulp_auto_us_cc_df_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_20/ulp_s00_regslice_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_20 || ORIG_REF_NAME==ulp_s00_regslice_20} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_21/ulp_s00_regslice_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_21 || ORIG_REF_NAME==ulp_s00_regslice_21} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s01_regslice_2/ulp_s01_regslice_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s01_regslice_2 || ORIG_REF_NAME==ulp_s01_regslice_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s02_regslice_0/ulp_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s02_regslice_0 || ORIG_REF_NAME==ulp_s02_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s03_regslice_0/ulp_s03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s03_regslice_0 || ORIG_REF_NAME==ulp_s03_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_us_0/ulp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_us_0 || ORIG_REF_NAME==ulp_auto_us_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_rs_w_0/ulp_auto_rs_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_rs_w_0 || ORIG_REF_NAME==ulp_auto_rs_w_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_2/ulp_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_2 || ORIG_REF_NAME==ulp_auto_cc_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s03_mmu_0/ulp_s03_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s03_mmu_0 || ORIG_REF_NAME==ulp_s03_mmu_0} -quiet] -quiet

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp'. Do not add the DONT_TOUCH constraint.

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/output/ulp_ooc_copy.xdc

# Block Designs: bd/ulp/ulp.bd
# Block Designs: The module: 'ulp' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ulp/ip/ulp_ii_level0_wire_0/ulp_ii_level0_wire_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_0 || ORIG_REF_NAME==ulp_ii_level0_wire_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_bram_ctrl_0_0/ulp_axi_bram_ctrl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ulp_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_bram_ctrl_0_bram_0/ulp_axi_bram_ctrl_0_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==ulp_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_0_0/ulp_axi_interconnect_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_0_0 || ORIG_REF_NAME==ulp_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_0_p_0/ulp_axi_interconnect_0_p_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_0_p_0 || ORIG_REF_NAME==ulp_axi_interconnect_0_p_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_1_0/ulp_axi_interconnect_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_1_0 || ORIG_REF_NAME==ulp_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_0_0/ulp_axi_vip_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_0_0 || ORIG_REF_NAME==ulp_axi_vip_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_0_p_0/ulp_axi_vip_0_p_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_0_p_0 || ORIG_REF_NAME==ulp_axi_vip_0_p_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ddr1_clk_bufg_0/ulp_ddr1_clk_bufg_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ddr1_clk_bufg_0 || ORIG_REF_NAME==ulp_ddr1_clk_bufg_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ddr1_clk_ibufds_0/ulp_ddr1_clk_ibufds_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ddr1_clk_ibufds_0 || ORIG_REF_NAME==ulp_ddr1_clk_ibufds_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ddrmem_1_0/ulp_ddrmem_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ddrmem_1_0 || ORIG_REF_NAME==ulp_ddrmem_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_0_0/ulp_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_0_0 || ORIG_REF_NAME==ulp_xlslice_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_1_0/ulp_xlslice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_1_0 || ORIG_REF_NAME==ulp_xlslice_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_2_0/ulp_xlslice_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_2_0 || ORIG_REF_NAME==ulp_xlslice_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_3_0/ulp_xlslice_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_3_0 || ORIG_REF_NAME==ulp_xlslice_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlslice_4_0/ulp_xlslice_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlslice_4_0 || ORIG_REF_NAME==ulp_xlslice_4_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_0/ulp_xlconcat_interrupt_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_0_0/ulp_xlconcat_interrupt_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_0_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_1_0/ulp_xlconcat_interrupt_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_1_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_2_0/ulp_xlconcat_interrupt_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_2_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconcat_interrupt_3_0/ulp_xlconcat_interrupt_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconcat_interrupt_3_0 || ORIG_REF_NAME==ulp_xlconcat_interrupt_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xlconstant_gnd_0/ulp_xlconstant_gnd_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xlconstant_gnd_0 || ORIG_REF_NAME==ulp_xlconstant_gnd_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_ddrmem_n_1_0/ulp_psreset_ddrmem_n_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_ddrmem_n_1_0 || ORIG_REF_NAME==ulp_psreset_ddrmem_n_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_periph_null_0/ulp_regslice_periph_null_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_periph_null_0 || ORIG_REF_NAME==ulp_regslice_periph_null_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_user_debug_bridge_0/ulp_user_debug_bridge_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_user_debug_bridge_0 || ORIG_REF_NAME==ulp_user_debug_bridge_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_debug_bridge_xsdbm_0/ulp_debug_bridge_xsdbm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_debug_bridge_xsdbm_0 || ORIG_REF_NAME==ulp_debug_bridge_xsdbm_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_fpga_dna_module_0_0/ulp_fpga_dna_module_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_fpga_dna_module_0_0 || ORIG_REF_NAME==ulp_fpga_dna_module_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_protocol_convert_0_0/ulp_axi_protocol_convert_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_protocol_convert_0_0 || ORIG_REF_NAME==ulp_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_cdc_data_static_0/ulp_axi_cdc_data_static_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_cdc_data_static_0 || ORIG_REF_NAME==ulp_axi_cdc_data_static_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_cdc_data_static1_0/ulp_axi_cdc_data_static1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_cdc_data_static1_0 || ORIG_REF_NAME==ulp_axi_cdc_data_static1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_gpio_null_0/ulp_axi_gpio_null_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_gpio_null_0 || ORIG_REF_NAME==ulp_axi_gpio_null_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_interconnect_0_1/ulp_axi_interconnect_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_interconnect_0_1 || ORIG_REF_NAME==ulp_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_ctrl_mgntpf_0/ulp_axi_vip_ctrl_mgntpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_ctrl_mgntpf_0 || ORIG_REF_NAME==ulp_axi_vip_ctrl_mgntpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_ctrl_userpf_0/ulp_axi_vip_ctrl_userpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_ctrl_userpf_0 || ORIG_REF_NAME==ulp_axi_vip_ctrl_userpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_data_static_0/ulp_axi_vip_data_static_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_data_static_0 || ORIG_REF_NAME==ulp_axi_vip_data_static_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_axi_vip_data_static1_0/ulp_axi_vip_data_static1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_axi_vip_data_static1_0 || ORIG_REF_NAME==ulp_axi_vip_data_static1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_freq_counter_0_0/ulp_freq_counter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_freq_counter_0_0 || ORIG_REF_NAME==ulp_freq_counter_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_interconnect_axilite_user_0/ulp_interconnect_axilite_user_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_interconnect_axilite_user_0 || ORIG_REF_NAME==ulp_interconnect_axilite_user_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_control_mgntpf_0/ulp_regslice_control_mgntpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_control_mgntpf_0 || ORIG_REF_NAME==ulp_regslice_control_mgntpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_control_userpf_0/ulp_regslice_control_userpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_control_userpf_0 || ORIG_REF_NAME==ulp_regslice_control_userpf_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_data_static_0/ulp_regslice_data_static_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_data_static_0 || ORIG_REF_NAME==ulp_regslice_data_static_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_regslice_data_static1_0/ulp_regslice_data_static1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_regslice_data_static1_0 || ORIG_REF_NAME==ulp_regslice_data_static1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_logic_reset_op_0/ulp_logic_reset_op_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_logic_reset_op_0 || ORIG_REF_NAME==ulp_logic_reset_op_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_control_0/ulp_psreset_gate_pr_control_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_control_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_control_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_data_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_data_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_ddrmem_1_0/ulp_psreset_gate_pr_ddrmem_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_ddrmem_1_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_ddrmem_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_kernel_0/ulp_psreset_gate_pr_kernel_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_kernel_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_kernel_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_psreset_gate_pr_kernel2_0/ulp_psreset_gate_pr_kernel2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_psreset_gate_pr_kernel2_0 || ORIG_REF_NAME==ulp_psreset_gate_pr_kernel2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_3/ulp_xbar_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_3 || ORIG_REF_NAME==ulp_xbar_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_2/ulp_xbar_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_2 || ORIG_REF_NAME==ulp_xbar_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_5/ulp_xbar_5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_5 || ORIG_REF_NAME==ulp_xbar_5} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_4/ulp_xbar_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_4 || ORIG_REF_NAME==ulp_xbar_4} -quiet] -quiet

# IP: bd/ulp/ip/ulp_krnl_ro_rtl_1_0/ulp_krnl_ro_rtl_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_krnl_ro_rtl_1_0 || ORIG_REF_NAME==ulp_krnl_ro_rtl_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0/ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0 || ORIG_REF_NAME==ulp_ii_level0_wire_ulp_s_irq_cu_00_1_interrupt_concat_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_irq_const_tieoff_0/ulp_irq_const_tieoff_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_irq_const_tieoff_0 || ORIG_REF_NAME==ulp_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_0 || ORIG_REF_NAME==ulp_auto_cc_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_22/ulp_s00_regslice_22.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_22 || ORIG_REF_NAME==ulp_s00_regslice_22} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m00_regslice_0/ulp_m00_regslice_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m00_regslice_0 || ORIG_REF_NAME==ulp_m00_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m01_regslice_0/ulp_m01_regslice_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m01_regslice_0 || ORIG_REF_NAME==ulp_m01_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_1/ulp_auto_cc_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_1 || ORIG_REF_NAME==ulp_auto_cc_1} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_19/ulp_s00_regslice_19.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_19 || ORIG_REF_NAME==ulp_s00_regslice_19} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s01_regslice_1/ulp_s01_regslice_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s01_regslice_1 || ORIG_REF_NAME==ulp_s01_regslice_1} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_us_cc_df_0/ulp_auto_us_cc_df_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_us_cc_df_0 || ORIG_REF_NAME==ulp_auto_us_cc_df_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_20/ulp_s00_regslice_20.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_20 || ORIG_REF_NAME==ulp_s00_regslice_20} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_21/ulp_s00_regslice_21.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_21 || ORIG_REF_NAME==ulp_s00_regslice_21} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s01_regslice_2/ulp_s01_regslice_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s01_regslice_2 || ORIG_REF_NAME==ulp_s01_regslice_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s02_regslice_0/ulp_s02_regslice_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s02_regslice_0 || ORIG_REF_NAME==ulp_s02_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s03_regslice_0/ulp_s03_regslice_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s03_regslice_0 || ORIG_REF_NAME==ulp_s03_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_us_0/ulp_auto_us_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_us_0 || ORIG_REF_NAME==ulp_auto_us_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_rs_w_0/ulp_auto_rs_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_rs_w_0 || ORIG_REF_NAME==ulp_auto_rs_w_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_2/ulp_auto_cc_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_2 || ORIG_REF_NAME==ulp_auto_cc_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s03_mmu_0/ulp_s03_mmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s03_mmu_0 || ORIG_REF_NAME==ulp_s03_mmu_0} -quiet] -quiet

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp'. Do not add the DONT_TOUCH constraint.

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/output/ulp_ooc_copy.xdc
