# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0.xci
# IP: The module: 'ulp_psreset_gate_pr_data_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_psreset_gate_pr_data_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_psreset_gate_pr_data_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_psreset_gate_pr_data_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0.xci
# IP: The module: 'ulp_psreset_gate_pr_data_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_psreset_gate_pr_data_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_psreset_gate_pr_data_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_psreset_gate_pr_data_0/ulp_psreset_gate_pr_data_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_psreset_gate_pr_data_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
