-- Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2021.1 (lin64) Build 3247384 Thu Jun 10 19:36:07 MDT 2021
-- Date        : Fri Dec 31 12:13:00 2021
-- Host        : caslab-cloudfpga running 64-bit Ubuntu 18.04.6 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/aee38/Documents/vitis_accel_examples/rtl_kernels/rtl_ro/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.vhdl
-- Design      : ulp
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcku15p-ffva1156-2LV-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity ulp is
  Port ( 
    BLP_S_AXI_CTRL_USER_00_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_00_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_00_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_00_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_00_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_00_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_00_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_00_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_00_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_00_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_01_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_01_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_01_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_01_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_01_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_01_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_01_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_01_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_01_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_02_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_02_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_02_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_02_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_02_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_02_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_02_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_02_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_02_wvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_araddr : in STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_00_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_arvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_awaddr : in STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_00_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_awvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_bready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_00_bvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_rdata : out STD_LOGIC_VECTOR ( 511 downto 0 );
    BLP_S_AXI_DATA_H2C_00_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_rlast : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_rready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_00_rvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_wdata : in STD_LOGIC_VECTOR ( 511 downto 0 );
    BLP_S_AXI_DATA_H2C_00_wlast : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_wready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_wstrb : in STD_LOGIC_VECTOR ( 63 downto 0 );
    BLP_S_AXI_DATA_H2C_00_wvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_araddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    BLP_S_AXI_DATA_H2C_01_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_01_arid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_01_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_01_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_01_arready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_arvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_awaddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    BLP_S_AXI_DATA_H2C_01_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_01_awid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_01_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_01_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_01_awready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_awvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_bid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_bready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_bvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    BLP_S_AXI_DATA_H2C_01_rid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_rlast : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_rready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_01_rvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    BLP_S_AXI_DATA_H2C_01_wlast : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_wready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_01_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_01_wvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_DATA_H2C_02_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_02_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_02_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_02_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_02_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_02_arready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_arvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_DATA_H2C_02_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_02_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_02_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_02_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_02_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_02_awready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_awvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_bready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_02_bvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_DATA_H2C_02_rlast : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_rready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_02_rvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_DATA_H2C_02_wlast : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_wready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_02_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_02_wvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_araddr : in STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_S_AXI_DATA_H2C_03_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_03_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_03_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_03_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_03_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_03_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_03_arready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_arvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_awaddr : in STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_S_AXI_DATA_H2C_03_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_03_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_03_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_03_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_03_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    BLP_S_AXI_DATA_H2C_03_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_DATA_H2C_03_awready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_awvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_03_bready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_03_bvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_rdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    BLP_S_AXI_DATA_H2C_03_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_03_rlast : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_rready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_03_rvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_wdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    BLP_S_AXI_DATA_H2C_03_wlast : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_wready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_03_wstrb : in STD_LOGIC_VECTOR ( 15 downto 0 );
    BLP_S_AXI_DATA_H2C_03_wvalid : in STD_LOGIC;
    blp_m_data_dna_from_ulp_00 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    blp_m_data_memory_calib_complete_00 : out STD_LOGIC_VECTOR ( 0 to 0 );
    blp_m_irq_cu_00 : out STD_LOGIC_VECTOR ( 127 downto 0 );
    blp_s_aclk_ctrl_00 : in STD_LOGIC;
    blp_s_aclk_kernel2_ref_clk_00 : in STD_LOGIC;
    blp_s_aclk_kernel_ref_clk_00 : in STD_LOGIC;
    blp_s_aclk_pcie_00 : in STD_LOGIC;
    blp_s_aresetn_ctrl_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_aresetn_kernel_ref_clk_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_aresetn_pcie_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_data_clkwiz_kernel_clk_out1_locked_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_data_dout_dna_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_data_perstn_out_00 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    blp_s_data_slice_pr_reset_to_ulp_00 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    io_clk_ddr_00_clk_n : in STD_LOGIC_VECTOR ( 0 to 0 );
    io_clk_ddr_00_clk_p : in STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_act_n : out STD_LOGIC;
    io_ddr_00_adr : out STD_LOGIC_VECTOR ( 16 downto 0 );
    io_ddr_00_ba : out STD_LOGIC_VECTOR ( 1 downto 0 );
    io_ddr_00_bg : out STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_ck_c : out STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_ck_t : out STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_cke : out STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_cs_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_dm_n : inout STD_LOGIC_VECTOR ( 8 downto 0 );
    io_ddr_00_dq : inout STD_LOGIC_VECTOR ( 71 downto 0 );
    io_ddr_00_dqs_c : inout STD_LOGIC_VECTOR ( 8 downto 0 );
    io_ddr_00_dqs_t : inout STD_LOGIC_VECTOR ( 8 downto 0 );
    io_ddr_00_odt : out STD_LOGIC_VECTOR ( 0 to 0 );
    io_ddr_00_reset_n : out STD_LOGIC
  );

end ulp;

architecture stub of ulp is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "BLP_S_AXI_CTRL_USER_00_araddr[24:0],BLP_S_AXI_CTRL_USER_00_arprot[2:0],BLP_S_AXI_CTRL_USER_00_arready,BLP_S_AXI_CTRL_USER_00_arvalid,BLP_S_AXI_CTRL_USER_00_awaddr[24:0],BLP_S_AXI_CTRL_USER_00_awprot[2:0],BLP_S_AXI_CTRL_USER_00_awready,BLP_S_AXI_CTRL_USER_00_awvalid,BLP_S_AXI_CTRL_USER_00_bready,BLP_S_AXI_CTRL_USER_00_bresp[1:0],BLP_S_AXI_CTRL_USER_00_bvalid,BLP_S_AXI_CTRL_USER_00_rdata[31:0],BLP_S_AXI_CTRL_USER_00_rready,BLP_S_AXI_CTRL_USER_00_rresp[1:0],BLP_S_AXI_CTRL_USER_00_rvalid,BLP_S_AXI_CTRL_USER_00_wdata[31:0],BLP_S_AXI_CTRL_USER_00_wready,BLP_S_AXI_CTRL_USER_00_wstrb[3:0],BLP_S_AXI_CTRL_USER_00_wvalid,BLP_S_AXI_CTRL_USER_01_araddr[24:0],BLP_S_AXI_CTRL_USER_01_arprot[2:0],BLP_S_AXI_CTRL_USER_01_arready,BLP_S_AXI_CTRL_USER_01_arvalid,BLP_S_AXI_CTRL_USER_01_awaddr[24:0],BLP_S_AXI_CTRL_USER_01_awprot[2:0],BLP_S_AXI_CTRL_USER_01_awready,BLP_S_AXI_CTRL_USER_01_awvalid,BLP_S_AXI_CTRL_USER_01_bready,BLP_S_AXI_CTRL_USER_01_bresp[1:0],BLP_S_AXI_CTRL_USER_01_bvalid,BLP_S_AXI_CTRL_USER_01_rdata[31:0],BLP_S_AXI_CTRL_USER_01_rready,BLP_S_AXI_CTRL_USER_01_rresp[1:0],BLP_S_AXI_CTRL_USER_01_rvalid,BLP_S_AXI_CTRL_USER_01_wdata[31:0],BLP_S_AXI_CTRL_USER_01_wready,BLP_S_AXI_CTRL_USER_01_wstrb[3:0],BLP_S_AXI_CTRL_USER_01_wvalid,BLP_S_AXI_CTRL_USER_02_araddr[24:0],BLP_S_AXI_CTRL_USER_02_arprot[2:0],BLP_S_AXI_CTRL_USER_02_arready,BLP_S_AXI_CTRL_USER_02_arvalid,BLP_S_AXI_CTRL_USER_02_awaddr[24:0],BLP_S_AXI_CTRL_USER_02_awprot[2:0],BLP_S_AXI_CTRL_USER_02_awready,BLP_S_AXI_CTRL_USER_02_awvalid,BLP_S_AXI_CTRL_USER_02_bready,BLP_S_AXI_CTRL_USER_02_bresp[1:0],BLP_S_AXI_CTRL_USER_02_bvalid,BLP_S_AXI_CTRL_USER_02_rdata[31:0],BLP_S_AXI_CTRL_USER_02_rready,BLP_S_AXI_CTRL_USER_02_rresp[1:0],BLP_S_AXI_CTRL_USER_02_rvalid,BLP_S_AXI_CTRL_USER_02_wdata[31:0],BLP_S_AXI_CTRL_USER_02_wready,BLP_S_AXI_CTRL_USER_02_wstrb[3:0],BLP_S_AXI_CTRL_USER_02_wvalid,BLP_S_AXI_DATA_H2C_00_araddr[38:0],BLP_S_AXI_DATA_H2C_00_arburst[1:0],BLP_S_AXI_DATA_H2C_00_arcache[3:0],BLP_S_AXI_DATA_H2C_00_arid[3:0],BLP_S_AXI_DATA_H2C_00_arlen[7:0],BLP_S_AXI_DATA_H2C_00_arlock[0:0],BLP_S_AXI_DATA_H2C_00_arprot[2:0],BLP_S_AXI_DATA_H2C_00_arready,BLP_S_AXI_DATA_H2C_00_arvalid,BLP_S_AXI_DATA_H2C_00_awaddr[38:0],BLP_S_AXI_DATA_H2C_00_awburst[1:0],BLP_S_AXI_DATA_H2C_00_awcache[3:0],BLP_S_AXI_DATA_H2C_00_awid[3:0],BLP_S_AXI_DATA_H2C_00_awlen[7:0],BLP_S_AXI_DATA_H2C_00_awlock[0:0],BLP_S_AXI_DATA_H2C_00_awprot[2:0],BLP_S_AXI_DATA_H2C_00_awready,BLP_S_AXI_DATA_H2C_00_awvalid,BLP_S_AXI_DATA_H2C_00_bid[3:0],BLP_S_AXI_DATA_H2C_00_bready,BLP_S_AXI_DATA_H2C_00_bresp[1:0],BLP_S_AXI_DATA_H2C_00_bvalid,BLP_S_AXI_DATA_H2C_00_rdata[511:0],BLP_S_AXI_DATA_H2C_00_rid[3:0],BLP_S_AXI_DATA_H2C_00_rlast,BLP_S_AXI_DATA_H2C_00_rready,BLP_S_AXI_DATA_H2C_00_rresp[1:0],BLP_S_AXI_DATA_H2C_00_rvalid,BLP_S_AXI_DATA_H2C_00_wdata[511:0],BLP_S_AXI_DATA_H2C_00_wlast,BLP_S_AXI_DATA_H2C_00_wready,BLP_S_AXI_DATA_H2C_00_wstrb[63:0],BLP_S_AXI_DATA_H2C_00_wvalid,BLP_S_AXI_DATA_H2C_01_araddr[39:0],BLP_S_AXI_DATA_H2C_01_arburst[1:0],BLP_S_AXI_DATA_H2C_01_arcache[3:0],BLP_S_AXI_DATA_H2C_01_arid[1:0],BLP_S_AXI_DATA_H2C_01_arlen[7:0],BLP_S_AXI_DATA_H2C_01_arlock[0:0],BLP_S_AXI_DATA_H2C_01_arprot[2:0],BLP_S_AXI_DATA_H2C_01_arready,BLP_S_AXI_DATA_H2C_01_arvalid,BLP_S_AXI_DATA_H2C_01_awaddr[39:0],BLP_S_AXI_DATA_H2C_01_awburst[1:0],BLP_S_AXI_DATA_H2C_01_awcache[3:0],BLP_S_AXI_DATA_H2C_01_awid[1:0],BLP_S_AXI_DATA_H2C_01_awlen[7:0],BLP_S_AXI_DATA_H2C_01_awlock[0:0],BLP_S_AXI_DATA_H2C_01_awprot[2:0],BLP_S_AXI_DATA_H2C_01_awready,BLP_S_AXI_DATA_H2C_01_awvalid,BLP_S_AXI_DATA_H2C_01_bid[1:0],BLP_S_AXI_DATA_H2C_01_bready,BLP_S_AXI_DATA_H2C_01_bresp[1:0],BLP_S_AXI_DATA_H2C_01_bvalid,BLP_S_AXI_DATA_H2C_01_rdata[63:0],BLP_S_AXI_DATA_H2C_01_rid[1:0],BLP_S_AXI_DATA_H2C_01_rlast,BLP_S_AXI_DATA_H2C_01_rready,BLP_S_AXI_DATA_H2C_01_rresp[1:0],BLP_S_AXI_DATA_H2C_01_rvalid,BLP_S_AXI_DATA_H2C_01_wdata[63:0],BLP_S_AXI_DATA_H2C_01_wlast,BLP_S_AXI_DATA_H2C_01_wready,BLP_S_AXI_DATA_H2C_01_wstrb[7:0],BLP_S_AXI_DATA_H2C_01_wvalid,BLP_S_AXI_DATA_H2C_02_araddr[31:0],BLP_S_AXI_DATA_H2C_02_arburst[1:0],BLP_S_AXI_DATA_H2C_02_arcache[3:0],BLP_S_AXI_DATA_H2C_02_arlen[7:0],BLP_S_AXI_DATA_H2C_02_arlock[0:0],BLP_S_AXI_DATA_H2C_02_arprot[2:0],BLP_S_AXI_DATA_H2C_02_arready,BLP_S_AXI_DATA_H2C_02_arvalid,BLP_S_AXI_DATA_H2C_02_awaddr[31:0],BLP_S_AXI_DATA_H2C_02_awburst[1:0],BLP_S_AXI_DATA_H2C_02_awcache[3:0],BLP_S_AXI_DATA_H2C_02_awlen[7:0],BLP_S_AXI_DATA_H2C_02_awlock[0:0],BLP_S_AXI_DATA_H2C_02_awprot[2:0],BLP_S_AXI_DATA_H2C_02_awready,BLP_S_AXI_DATA_H2C_02_awvalid,BLP_S_AXI_DATA_H2C_02_bready,BLP_S_AXI_DATA_H2C_02_bresp[1:0],BLP_S_AXI_DATA_H2C_02_bvalid,BLP_S_AXI_DATA_H2C_02_rdata[31:0],BLP_S_AXI_DATA_H2C_02_rlast,BLP_S_AXI_DATA_H2C_02_rready,BLP_S_AXI_DATA_H2C_02_rresp[1:0],BLP_S_AXI_DATA_H2C_02_rvalid,BLP_S_AXI_DATA_H2C_02_wdata[31:0],BLP_S_AXI_DATA_H2C_02_wlast,BLP_S_AXI_DATA_H2C_02_wready,BLP_S_AXI_DATA_H2C_02_wstrb[3:0],BLP_S_AXI_DATA_H2C_02_wvalid,BLP_S_AXI_DATA_H2C_03_araddr[38:0],BLP_S_AXI_DATA_H2C_03_arburst[1:0],BLP_S_AXI_DATA_H2C_03_arcache[3:0],BLP_S_AXI_DATA_H2C_03_arid[3:0],BLP_S_AXI_DATA_H2C_03_arlen[7:0],BLP_S_AXI_DATA_H2C_03_arlock[0:0],BLP_S_AXI_DATA_H2C_03_arprot[2:0],BLP_S_AXI_DATA_H2C_03_arready,BLP_S_AXI_DATA_H2C_03_arvalid,BLP_S_AXI_DATA_H2C_03_awaddr[38:0],BLP_S_AXI_DATA_H2C_03_awburst[1:0],BLP_S_AXI_DATA_H2C_03_awcache[3:0],BLP_S_AXI_DATA_H2C_03_awid[3:0],BLP_S_AXI_DATA_H2C_03_awlen[7:0],BLP_S_AXI_DATA_H2C_03_awlock[0:0],BLP_S_AXI_DATA_H2C_03_awprot[2:0],BLP_S_AXI_DATA_H2C_03_awready,BLP_S_AXI_DATA_H2C_03_awvalid,BLP_S_AXI_DATA_H2C_03_bid[3:0],BLP_S_AXI_DATA_H2C_03_bready,BLP_S_AXI_DATA_H2C_03_bresp[1:0],BLP_S_AXI_DATA_H2C_03_bvalid,BLP_S_AXI_DATA_H2C_03_rdata[127:0],BLP_S_AXI_DATA_H2C_03_rid[3:0],BLP_S_AXI_DATA_H2C_03_rlast,BLP_S_AXI_DATA_H2C_03_rready,BLP_S_AXI_DATA_H2C_03_rresp[1:0],BLP_S_AXI_DATA_H2C_03_rvalid,BLP_S_AXI_DATA_H2C_03_wdata[127:0],BLP_S_AXI_DATA_H2C_03_wlast,BLP_S_AXI_DATA_H2C_03_wready,BLP_S_AXI_DATA_H2C_03_wstrb[15:0],BLP_S_AXI_DATA_H2C_03_wvalid,blp_m_data_dna_from_ulp_00[2:0],blp_m_data_memory_calib_complete_00[0:0],blp_m_irq_cu_00[127:0],blp_s_aclk_ctrl_00,blp_s_aclk_kernel2_ref_clk_00,blp_s_aclk_kernel_ref_clk_00,blp_s_aclk_pcie_00,blp_s_aresetn_ctrl_00[0:0],blp_s_aresetn_kernel_ref_clk_00[0:0],blp_s_aresetn_pcie_00[0:0],blp_s_data_clkwiz_kernel_clk_out1_locked_00[0:0],blp_s_data_dout_dna_00[0:0],blp_s_data_perstn_out_00[2:0],blp_s_data_slice_pr_reset_to_ulp_00[1:0],io_clk_ddr_00_clk_n[0:0],io_clk_ddr_00_clk_p[0:0],io_ddr_00_act_n,io_ddr_00_adr[16:0],io_ddr_00_ba[1:0],io_ddr_00_bg[0:0],io_ddr_00_ck_c[0:0],io_ddr_00_ck_t[0:0],io_ddr_00_cke[0:0],io_ddr_00_cs_n[0:0],io_ddr_00_dm_n[8:0],io_ddr_00_dq[71:0],io_ddr_00_dqs_c[8:0],io_ddr_00_dqs_t[8:0],io_ddr_00_odt[0:0],io_ddr_00_reset_n";
begin
end;
