proc init {cellpath otherinfo} {
   set cellobj [get_bd_cells $cellpath]
   bd::mark_propagate_overrideable $cellobj [list C2_DDR_SAXI_ID_WIDTH C2_DDR_SAXI_DATA_WIDTH C2_DDR_SAXI_ADDR_WIDTH C2_DDR_SAXI_AWUSER_WIDTH C2_DDR_SAXI_ARUSER_WIDTH C2_DDR_SAXI_WUSER_WIDTH C2_DDR_SAXI_RUSER_WIDTH C2_DDR_SAXI_BUSER_WIDTH C0_DDR_SAXI_ID_WIDTH C0_DDR_SAXI_DATA_WIDTH C0_DDR_SAXI_ADDR_WIDTH C0_DDR_SAXI_AWUSER_WIDTH C0_DDR_SAXI_ARUSER_WIDTH C0_DDR_SAXI_WUSER_WIDTH C0_DDR_SAXI_RUSER_WIDTH C0_DDR_SAXI_BUSER_WIDTH C1_DDR_SAXI_ID_WIDTH C1_DDR_SAXI_DATA_WIDTH C1_DDR_SAXI_ADDR_WIDTH C1_DDR_SAXI_AWUSER_WIDTH C1_DDR_SAXI_ARUSER_WIDTH C1_DDR_SAXI_WUSER_WIDTH C1_DDR_SAXI_RUSER_WIDTH C1_DDR_SAXI_BUSER_WIDTH C3_DDR_SAXI_ID_WIDTH C3_DDR_SAXI_DATA_WIDTH C3_DDR_SAXI_ADDR_WIDTH C3_DDR_SAXI_AWUSER_WIDTH C3_DDR_SAXI_ARUSER_WIDTH C3_DDR_SAXI_WUSER_WIDTH C3_DDR_SAXI_RUSER_WIDTH C3_DDR_SAXI_BUSER_WIDTH C_S_XDMA_AXI_ID_WIDTH C_S_XDMA_AXI_DATA_WIDTH C_S_XDMA_AXI_ADDR_WIDTH C_S_XDMA_AXI_AWUSER_WIDTH C_S_XDMA_AXI_ARUSER_WIDTH C_S_XDMA_AXI_WUSER_WIDTH C_S_XDMA_AXI_RUSER_WIDTH C_S_XDMA_AXI_BUSER_WIDTH]
   
}

proc propagate {cellpath otherinfo} {

   set cellobj [get_bd_cells $cellpath]
   set port_handle [get_bd_intf_pins $cellobj/C0_DDR_SAXI]
   if { $port_handle != ""} {
     set C0_DDR_SAXI_ADDR_WIDTH [get_property CONFIG.ADDR_WIDTH $port_handle]
     set C0_DDR_SAXI_ARUSER_WIDTH [get_property CONFIG.ARUSER_WIDTH $port_handle]
     set C0_DDR_SAXI_AWUSER_WIDTH [get_property CONFIG.AWUSER_WIDTH $port_handle]
     set C0_DDR_SAXI_BUSER_WIDTH [get_property CONFIG.BUSER_WIDTH $port_handle]
     set C0_DDR_SAXI_DATA_WIDTH [get_property CONFIG.DATA_WIDTH $port_handle]
     set C0_DDR_SAXI_ID_WIDTH [get_property CONFIG.ID_WIDTH $port_handle]
     set C0_DDR_SAXI_RUSER_WIDTH [get_property CONFIG.RUSER_WIDTH $port_handle]
     set C0_DDR_SAXI_WUSER_WIDTH [get_property CONFIG.WUSER_WIDTH $port_handle]

     set_property -dict [list CONFIG.C0_DDR_SAXI_ADDR_WIDTH $C0_DDR_SAXI_ADDR_WIDTH CONFIG.C0_DDR_SAXI_ARUSER_WIDTH $C0_DDR_SAXI_ARUSER_WIDTH CONFIG.C0_DDR_SAXI_AWUSER_WIDTH $C0_DDR_SAXI_AWUSER_WIDTH CONFIG.C0_DDR_SAXI_BUSER_WIDTH $C0_DDR_SAXI_BUSER_WIDTH CONFIG.C0_DDR_SAXI_DATA_WIDTH $C0_DDR_SAXI_DATA_WIDTH CONFIG.C0_DDR_SAXI_ID_WIDTH $C0_DDR_SAXI_ID_WIDTH CONFIG.C0_DDR_SAXI_RUSER_WIDTH $C0_DDR_SAXI_RUSER_WIDTH CONFIG.C0_DDR_SAXI_WUSER_WIDTH $C0_DDR_SAXI_WUSER_WIDTH] $cellobj
   }
   set cellobj [get_bd_cells $cellpath]
   set port_handle [get_bd_intf_pins $cellobj/C1_DDR_SAXI]
   if { $port_handle != ""} {
     set C1_DDR_SAXI_ADDR_WIDTH [get_property CONFIG.ADDR_WIDTH $port_handle]
     set C1_DDR_SAXI_ARUSER_WIDTH [get_property CONFIG.ARUSER_WIDTH $port_handle]
     set C1_DDR_SAXI_AWUSER_WIDTH [get_property CONFIG.AWUSER_WIDTH $port_handle]
     set C1_DDR_SAXI_BUSER_WIDTH [get_property CONFIG.BUSER_WIDTH $port_handle]
     set C1_DDR_SAXI_DATA_WIDTH [get_property CONFIG.DATA_WIDTH $port_handle]
     set C1_DDR_SAXI_ID_WIDTH [get_property CONFIG.ID_WIDTH $port_handle]
     set C1_DDR_SAXI_RUSER_WIDTH [get_property CONFIG.RUSER_WIDTH $port_handle]
     set C1_DDR_SAXI_WUSER_WIDTH [get_property CONFIG.WUSER_WIDTH $port_handle]

     set_property -dict [list CONFIG.C1_DDR_SAXI_ADDR_WIDTH $C1_DDR_SAXI_ADDR_WIDTH CONFIG.C1_DDR_SAXI_ARUSER_WIDTH $C1_DDR_SAXI_ARUSER_WIDTH CONFIG.C1_DDR_SAXI_AWUSER_WIDTH $C1_DDR_SAXI_AWUSER_WIDTH CONFIG.C1_DDR_SAXI_BUSER_WIDTH $C1_DDR_SAXI_BUSER_WIDTH CONFIG.C1_DDR_SAXI_DATA_WIDTH $C1_DDR_SAXI_DATA_WIDTH CONFIG.C1_DDR_SAXI_ID_WIDTH $C1_DDR_SAXI_ID_WIDTH CONFIG.C1_DDR_SAXI_RUSER_WIDTH $C1_DDR_SAXI_RUSER_WIDTH CONFIG.C1_DDR_SAXI_WUSER_WIDTH $C1_DDR_SAXI_WUSER_WIDTH] $cellobj
   }
   set cellobj [get_bd_cells $cellpath]
   set port_handle [get_bd_intf_pins $cellobj/C2_DDR_SAXI]
   if { $port_handle != ""} {
     set C2_DDR_SAXI_ADDR_WIDTH [get_property CONFIG.ADDR_WIDTH $port_handle]
     set C2_DDR_SAXI_ARUSER_WIDTH [get_property CONFIG.ARUSER_WIDTH $port_handle]
     set C2_DDR_SAXI_AWUSER_WIDTH [get_property CONFIG.AWUSER_WIDTH $port_handle]
     set C2_DDR_SAXI_BUSER_WIDTH [get_property CONFIG.BUSER_WIDTH $port_handle]
     set C2_DDR_SAXI_DATA_WIDTH [get_property CONFIG.DATA_WIDTH $port_handle]
     set C2_DDR_SAXI_ID_WIDTH [get_property CONFIG.ID_WIDTH $port_handle]
     set C2_DDR_SAXI_RUSER_WIDTH [get_property CONFIG.RUSER_WIDTH $port_handle]
     set C2_DDR_SAXI_WUSER_WIDTH [get_property CONFIG.WUSER_WIDTH $port_handle]

     set_property -dict [list CONFIG.C2_DDR_SAXI_ADDR_WIDTH $C2_DDR_SAXI_ADDR_WIDTH CONFIG.C2_DDR_SAXI_ARUSER_WIDTH $C2_DDR_SAXI_ARUSER_WIDTH CONFIG.C2_DDR_SAXI_AWUSER_WIDTH $C2_DDR_SAXI_AWUSER_WIDTH CONFIG.C2_DDR_SAXI_BUSER_WIDTH $C2_DDR_SAXI_BUSER_WIDTH CONFIG.C2_DDR_SAXI_DATA_WIDTH $C2_DDR_SAXI_DATA_WIDTH CONFIG.C2_DDR_SAXI_ID_WIDTH $C2_DDR_SAXI_ID_WIDTH CONFIG.C2_DDR_SAXI_RUSER_WIDTH $C2_DDR_SAXI_RUSER_WIDTH CONFIG.C2_DDR_SAXI_WUSER_WIDTH $C2_DDR_SAXI_WUSER_WIDTH] $cellobj
   }
   set cellobj [get_bd_cells $cellpath]
   set port_handle [get_bd_intf_pins $cellobj/C3_DDR_SAXI]
   if { $port_handle != ""} {
     set C3_DDR_SAXI_ADDR_WIDTH [get_property CONFIG.ADDR_WIDTH $port_handle]
     set C3_DDR_SAXI_ARUSER_WIDTH [get_property CONFIG.ARUSER_WIDTH $port_handle]
     set C3_DDR_SAXI_AWUSER_WIDTH [get_property CONFIG.AWUSER_WIDTH $port_handle]
     set C3_DDR_SAXI_BUSER_WIDTH [get_property CONFIG.BUSER_WIDTH $port_handle]
     set C3_DDR_SAXI_DATA_WIDTH [get_property CONFIG.DATA_WIDTH $port_handle]
     set C3_DDR_SAXI_ID_WIDTH [get_property CONFIG.ID_WIDTH $port_handle]
     set C3_DDR_SAXI_RUSER_WIDTH [get_property CONFIG.RUSER_WIDTH $port_handle]
     set C3_DDR_SAXI_WUSER_WIDTH [get_property CONFIG.WUSER_WIDTH $port_handle]

     set_property -dict [list CONFIG.C3_DDR_SAXI_ADDR_WIDTH $C3_DDR_SAXI_ADDR_WIDTH CONFIG.C3_DDR_SAXI_ARUSER_WIDTH $C3_DDR_SAXI_ARUSER_WIDTH CONFIG.C3_DDR_SAXI_AWUSER_WIDTH $C3_DDR_SAXI_AWUSER_WIDTH CONFIG.C3_DDR_SAXI_BUSER_WIDTH $C3_DDR_SAXI_BUSER_WIDTH CONFIG.C3_DDR_SAXI_DATA_WIDTH $C3_DDR_SAXI_DATA_WIDTH CONFIG.C3_DDR_SAXI_ID_WIDTH $C3_DDR_SAXI_ID_WIDTH CONFIG.C3_DDR_SAXI_RUSER_WIDTH $C3_DDR_SAXI_RUSER_WIDTH CONFIG.C3_DDR_SAXI_WUSER_WIDTH $C3_DDR_SAXI_WUSER_WIDTH] $cellobj
   }
   set cellobj [get_bd_cells $cellpath]
   set port_handle [get_bd_intf_pins $cellobj/S_XDMA_AXI]
   if { $port_handle != ""} {
     set C_S_XDMA_AXI_ADDR_WIDTH [get_property CONFIG.ADDR_WIDTH $port_handle]
     set C_S_XDMA_AXI_ARUSER_WIDTH [get_property CONFIG.ARUSER_WIDTH $port_handle]
     set C_S_XDMA_AXI_AWUSER_WIDTH [get_property CONFIG.AWUSER_WIDTH $port_handle]
     set C_S_XDMA_AXI_BUSER_WIDTH [get_property CONFIG.BUSER_WIDTH $port_handle]
     set C_S_XDMA_AXI_DATA_WIDTH [get_property CONFIG.DATA_WIDTH $port_handle]
     set C_S_XDMA_AXI_ID_WIDTH [get_property CONFIG.ID_WIDTH $port_handle]
     set C_S_XDMA_AXI_RUSER_WIDTH [get_property CONFIG.RUSER_WIDTH $port_handle]
     set C_S_XDMA_AXI_WUSER_WIDTH [get_property CONFIG.WUSER_WIDTH $port_handle]

     set_property -dict [list CONFIG.C_S_XDMA_AXI_ADDR_WIDTH $C_S_XDMA_AXI_ADDR_WIDTH CONFIG.C_S_XDMA_AXI_ARUSER_WIDTH $C_S_XDMA_AXI_ARUSER_WIDTH CONFIG.C_S_XDMA_AXI_AWUSER_WIDTH $C_S_XDMA_AXI_AWUSER_WIDTH CONFIG.C_S_XDMA_AXI_BUSER_WIDTH $C_S_XDMA_AXI_BUSER_WIDTH CONFIG.C_S_XDMA_AXI_DATA_WIDTH $C_S_XDMA_AXI_DATA_WIDTH CONFIG.C_S_XDMA_AXI_ID_WIDTH $C_S_XDMA_AXI_ID_WIDTH CONFIG.C_S_XDMA_AXI_RUSER_WIDTH $C_S_XDMA_AXI_RUSER_WIDTH CONFIG.C_S_XDMA_AXI_WUSER_WIDTH $C_S_XDMA_AXI_WUSER_WIDTH] $cellobj
   }
}
