# This file was automatically generated by Vpl
write_user_impl_clock_constraint "level0_i/ulp" "blp_s_aclk_kernel2_ref_clk_00 {is_user_set false instance _bd_top port blp_s_aclk_kernel2_ref_clk_00 clk_id 1 freq 500.000000} blp_s_aclk_kernel_ref_clk_00 {is_user_set false instance _bd_top port blp_s_aclk_kernel_ref_clk_00 clk_id 0 freq 300.000000}" "" $vivado_output_dir
